# path to your resume.json
json_resume_path: "resume.json"

# pt or en
# leave empty to use system
language: "en"

# override for the header
# leave empty if you want to use the one on your resume.json
name: ""

colors:
  name: "000000"
  heading: "0e6d24"
  tagline: "000000"
  headingrule: "0e6d24"
  accent: "21BA45"
  emphasis: "000000"
  body: "666666"

composition:
  first-column:
    - work
    - technical-skills
    - new-page
    - certificates
  second-column:
    - education
    - volunteer
    - languages
    - soft-skills
    - awards

strings:
  work: Work Experience
  technical-skills: Technical Skills
  certificates: Certificates
